typography_spectrum: 0.32708
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.125
  lightness: 0.5625
  saturation: 0.75
  rhythmicContrast: 0.25
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Derek Punsalan
  email: derek@punsalan.me
name: Derek
cta:
  domain: null
  bucket: null
  version: null
favicon: null
purpose: []
