name: Derek
favicon: null
layout_spectrum: 0.49666
typography_spectrum: 0.5233886872883886
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.5
  lightness: 0.9314139140769839
  saturation: 0.9294850206933916
  rhythmicContrast: 0.5358450079802424
purpose: []
